// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtEGRT0OIm5weabUqiPheZOUfduykqGa4',
    appId: '1:416486319043:web:cc63d002d93c0fd7cf9376',
    messagingSenderId: '416486319043',
    projectId: 'app-breezy',
    authDomain: 'app-breezy.firebaseapp.com',
    storageBucket: 'app-breezy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWw9fME-ZPNQa4uTZjqnXWfsTtKk5NoKE',
    appId: '1:416486319043:android:fd8fbfe9a4e9bff8cf9376',
    messagingSenderId: '416486319043',
    projectId: 'app-breezy',
    storageBucket: 'app-breezy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxI_rdvbHfrDxwPIc305YPL7flRxW6D4w',
    appId: '1:416486319043:ios:77e0a392c16e1b2bcf9376',
    messagingSenderId: '416486319043',
    projectId: 'app-breezy',
    storageBucket: 'app-breezy.firebasestorage.app',
    iosBundleId: 'com.nakiganda.breezy',
  );

}